-- Завдання 1
SELECT DISTINCT O.MFR
FROM dbo.ORDERS O
INNER JOIN dbo.CUSTOMERS C ON O.CUST = C.CUST_NUM
WHERE O.ORDER_DATE >= '2008-01-01' AND O.ORDER_DATE < '2009-01-01'
  AND C.COMPANY LIKE '%CORP%'
ORDER BY O.MFR;

--ЗАВДАННЯ 2
SELECT 
    C.CUST_NUM, 
    MONTH(O.ORDER_DATE) AS OrderMonth,
    COUNT(DISTINCT O.ORDER_NUM) AS UniqueOrderCount
FROM dbo.CUSTOMERS C
LEFT JOIN dbo.ORDERS O 
    ON C.CUST_NUM = O.CUST
    AND O.ORDER_DATE >= '2008-01-01' 
    AND O.ORDER_DATE < '2009-01-01'
WHERE C.COMPANY LIKE '%CORP%'
GROUP BY C.CUST_NUM, MONTH(O.ORDER_DATE)
ORDER BY UniqueOrderCount DESC;

-- ЗАВДАННЯ 3
SELECT 
    C.CUST_NUM, 
    UPPER(C.COMPANY) AS CompanyName, 
    P.[DESCRIPTION]
FROM dbo.CUSTOMERS C
LEFT JOIN dbo.ORDERS O ON C.CUST_NUM = O.CUST
    AND O.ORDER_DATE >= '2008-01-01' 
    AND O.ORDER_DATE < '2009-01-01'
LEFT JOIN dbo.PRODUCTS P ON O.PRODUCT = P.PRODUCT_ID
WHERE C.COMPANY LIKE '%CORP%'
GROUP BY C.CUST_NUM, UPPER(C.COMPANY), P.[DESCRIPTION]
ORDER BY C.CUST_NUM, P.[DESCRIPTION];

